import controlerImg from '../assets/images/cardImages/controler1.png';
import keyboardImg from '../assets/images/cardImages/keyboard.png';
import monitorImg from '../assets/images/cardImages/monitor1.png';
import chairImg from '../assets/images/cardImages/chair1.png';
import redJacketImg from '../assets/images/cardImages/redjacket.png';
import bagImg from '../assets/images/cardImages/bag.png';
import cpucoolerImg from '../assets/images/cardImages/cpucooler.png';
import bookshell from '../assets/images/cardImages/bookshell.svg';
import chocolate from '../assets/images/cardImages/chocolate.svg';
import dslr from '../assets/images/cardImages/dslr.svg';
import laptop from '../assets/images/cardImages/laptop.png';
import cream from '../assets/images/cardImages/cream.jpg';
import babycar from '../assets/images/cardImages/babycar.svg';
import boot from '../assets/images/cardImages/boot.svg';
import gamepad from '../assets/images/cardImages/gamepad.png';
import jacketImg from '../assets/images/cardImages/jacket.png';

const products = {
  today: [
    {
      id: 1,
      image: controlerImg,
      productName: "HAVIT HV-G92 Gamepad",
      rating: 5,
      starCount: 88,
      oldPrice: 160,
      newPrice: 120,
      offer: "-40%",
      reviews: [
        {
          user: "JohnD",
          comment: "Nice packaging, fast delivery.",
          rating: 4,
        },
        {
          user: "DarkHorse",
          comment: "Love the grip design.",
          rating: 3,
        },
        {
          user: "AliceW",
          comment: "Excellent responsiveness and build quality!",
          rating: 4,
        },
        {
          user: "JohnD",
          comment: "Packaging could be better.",
          rating: 3,
        },
        {
          user: "ArminZ",
          comment: "Packaging could be better.",
          rating: 3,
        },
        {
          user: "PixelGuy",
          comment: "Connectivity is fast and stable.",
          rating: 4,
        },
        {
          user: "ImranSK",
          comment: "Better than expected at this price.",
          rating: 3,
        },
        {
          user: "TariqA",
          comment: "Good value for money.",
          rating: 5,
        },
        {
          user: "ImranSK",
          comment: "Battery life is impressive.",
          rating: 4,
        },
        {
          user: "DarkHorse",
          comment: "Love the grip design.",
          rating: 4,
        },
      ],
    },
    {
      id: 2,
      image: keyboardImg,
      productName: "AK-900 Wired Keyboard",
      rating: 4.6,
      starCount: 75,
      oldPrice: 1160,
      newPrice: 960,
      offer: "-35%",
    },
    {
      id: 3,
      image: monitorImg,
      productName: "IPS LCD Gaming Monitor",
      rating: 4,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-30%",
    },
    {
      id: 4,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
    {
      id: 5,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
    {
      id: 6,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
    {
      id: 7,
      image: controlerImg,
      productName: "HAVIT HV-G92 Gamepad",
      rating: 5,
      starCount: 88,
      oldPrice: 160,
      newPrice: 120,
      offer: "-40%",
    },
    {
      id: 8,
      image: keyboardImg,
      productName: "AK-900 Wired Keyboard",
      rating: 4.6,
      starCount: 75,
      oldPrice: 1160,
      newPrice: 960,
      offer: "-35%",
    },
    {
      id: 9,
      image: monitorImg,
      productName: "IPS LCD Gaming Monitor",
      rating: 4,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-30%",
    },
    {
      id: 10,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
    {
      id: 11,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
    {
      id: 12,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
  ],
  thisMonth: [
    {
      id: 13,
      image: redJacketImg,
      productName: "The north coat",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 14,
      image: bagImg,
      productName: "Gucci duffle bag",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 15,
      image: cpucoolerImg,
      productName: "RGB liquid CPU Cooler",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 16,
      image: bookshell,
      productName: "Small BookShelf",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
  ],
  ourProducts: [
    {
      id: 17,
      image: chocolate,
      productName: "Breed Dry Dog Food",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 18,
      image: dslr,
      productName: "CANON EOS DSLR Camera",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 19,
      image: laptop,
      productName: "ASUS FHD Gaming Laptop",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 20,
      image: cream,
      productName: "Curology Product Set",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 21,
      image: babycar,
      productName: "Kids Electric Car",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 22,
      image: boot,
      productName: "Jr. Zoom Soccer Cleats",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 23,
      image: gamepad,
      productName: "GP11 Shooter USB Gamepad",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 24,
      image: jacketImg,
      productName: "Winter Jacket",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 25,
      image: gamepad,
      productName: "GP11 Shooter USB Gamepad",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 26,
      image: jacketImg,
      productName: "Winter Jacket",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 27,
      image: chocolate,
      productName: "Breed Dry Dog Food",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 28,
      image: dslr,
      productName: "CANON EOS DSLR Camera",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 29,
      image: laptop,
      productName: "ASUS FHD Gaming Laptop",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 30,
      image: cream,
      productName: "Curology Product Set",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 31,
      image: babycar,
      productName: "Kids Electric Car",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 32,
      image: boot,
      productName: "Jr. Zoom Soccer Cleats",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 33,
      image: gamepad,
      productName: "GP11 Shooter USB Gamepad",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 34,
      image: jacketImg,
      productName: "Winter Jacket",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 35,
      image: gamepad,
      productName: "GP11 Shooter USB Gamepad",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 36,
      image: jacketImg,
      productName: "Winter Jacket",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
  ],
  women: [
    {
      id: 37,
      image: redJacketImg,
      productName: "Stylish Red Jacket",
      rating: 4.5,
      starCount: 240,
      oldPrice: 1500,
      newPrice: 1250,
      offer: "-17%",
    }
  ],
  men: [
    {
      id: 38,
      image: jacketImg,
      productName: "Men's Winter Jacket",
      rating: 4.7,
      starCount: 330,
      oldPrice: 1800,
      newPrice: 1400,
      offer: "-22%",
    }
  ],
  electronics: [
    {
      id: 39,
      image: monitorImg,
      productName: "Gaming Monitor",
      rating: 4.4,
      starCount: 310,
      oldPrice: 900,
      newPrice: 750,
      offer: "-17%",
    }
  ],
  home: [
    {
      id: 40,
      image: bookshell,
      productName: "Modern Bookshelf",
      rating: 4.6,
      starCount: 120,
      oldPrice: 2000,
      newPrice: 1750,
      offer: "-12%",
    }
  ],
  medicine: [
    {
      id: 41,
      image: cream,
      productName: "Skincare Cream",
      rating: 4.3,
      starCount: 95,
      oldPrice: 400,
      newPrice: 350,
      offer: "-13%",
    }
  ],
  sports: [
    {
      id: 42,
      image: boot,
      productName: "Soccer Cleats",
      rating: 4.7,
      starCount: 300,
      oldPrice: 1000,
      newPrice: 850,
      offer: "-15%",
    }
  ],
  baby: [
    {
      id: 43,
      image: babycar,
      productName: "Kids Electric Car",
      rating: 4.8,
      starCount: 220,
      oldPrice: 5000,
      newPrice: 4200,
      offer: "-16%",
    }
  ],
  groceries: [
    {
      id: 44,
      image: chocolate,
      productName: "Dark Chocolate Pack",
      rating: 4.6,
      starCount: 180,
      oldPrice: 350,
      newPrice: 300,
      offer: "-14%",
    }
  ],
  health: [
    {
      id: 45,
      image: cream,
      productName: "Curology Skincare Set",
      rating: 4.8,
      starCount: 130,
      oldPrice: 1200,
      newPrice: 1050,
      offer: "-13%",
    }
  ],
  smartphone: [
    {
      id: 46,
      image: laptop,
      productName: "Smartphone Accessory Kit",
      rating: 4.5,
      starCount: 250,
      oldPrice: 700,
      newPrice: 600,
      offer: "-14%",
    }
  ],
  monitor: [
    {
      id: 47,
      image: monitorImg,
      productName: "HD Computer Monitor",
      rating: 4.7,
      starCount: 200,
      oldPrice: 1000,
      newPrice: 850,
      offer: "-15%",
    }
  ],
  watch: [
    {
      id: 48,
      image: bagImg,
      productName: "Digital Wrist Watch",
      rating: 4.2,
      starCount: 190,
      oldPrice: 1200,
      newPrice: 990,
      offer: "-18%",
    }
  ],
  camera: [
    {
      id: 49,
      image: dslr,
      productName: "Canon DSLR",
      rating: 4.9,
      starCount: 400,
      oldPrice: 3500,
      newPrice: 3000,
      offer: "-14%",
    }
  ],
  headphones: [
    {
      id: 50,
      image: cpucoolerImg,
      productName: "Wireless Headset",
      rating: 4.6,
      starCount: 220,
      oldPrice: 1300,
      newPrice: 1100,
      offer: "-15%",
    }
  ],
  gamepad: [
    {
      id: 51,
      image: gamepad,
      productName: "USB Gamepad",
      rating: 4.8,
      starCount: 290,
      oldPrice: 800,
      newPrice: 680,
      offer: "-15%",
    }
  ],
};

export default products;
