import controlerImg from '../assets/images/cardImages/controler.png';
import keyboardImg from '../assets/images/cardImages/keyboard.png';
import monitorImg from '../assets/images/cardImages/monitor.png';
import chairImg from '../assets/images/cardImages/chair.png';
import redJacketImg from '../assets/images/cardImages/redJacket.png';
import bagImg from '../assets/images/cardImages/bag.png';
import cpucoolerImg from '../assets/images/cardImages/cpucooler.png';
import bookshell from '../assets/images/cardImages/bookshell.svg';
import chocolate from '../assets/images/cardImages/chocolate.svg';
import dslr from '../assets/images/cardImages/dslr.svg';
import laptop from '../assets/images/cardImages/laptop.png';
import cream from '../assets/images/cardImages/cream.jpg';
import babycar from '../assets/images/cardImages/babycar.svg';
import boot from '../assets/images/cardImages/boot.svg';
import gamepad from '../assets/images/cardImages/gamepad.png';
import jacketImg from '../assets/images/cardImages/jacket.png';

const products = {
  today: [
    {
      id: 1,
      image: controlerImg,
      productName: "HAVIT HV-G92 Gamepad",
      rating: 5,
      starCount: 88,
      oldPrice: 160,
      newPrice: 120,
      offer: "-40%",
    },
    {
      id: 2,
      image: keyboardImg,
      productName: "AK-900 Wired Keyboard",
      rating: 4.6,
      starCount: 75,
      oldPrice: 1160,
      newPrice: 960,
      offer: "-35%",
    },
    {
      id: 3,
      image: monitorImg,
      productName: "IPS LCD Gaming Monitor",
      rating: 4,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-30%",
    },
    {
      id: 4,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
    {
      id: 30,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
    {
      id: 31,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
    {
      id: 1,
      image: controlerImg,
      productName: "HAVIT HV-G92 Gamepad",
      rating: 5,
      starCount: 88,
      oldPrice: 160,
      newPrice: 120,
      offer: "-40%",
    },
    {
      id: 2,
      image: keyboardImg,
      productName: "AK-900 Wired Keyboard",
      rating: 4.6,
      starCount: 75,
      oldPrice: 1160,
      newPrice: 960,
      offer: "-35%",
    },
    {
      id: 3,
      image: monitorImg,
      productName: "IPS LCD Gaming Monitor",
      rating: 4,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-30%",
    },
    {
      id: 4,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
    {
      id: 30,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
    {
      id: 31,
      image: chairImg,
      productName: "S-Series Comfort Chair",
      rating: 4.9,
      starCount: 99,
      oldPrice: 650,
      newPrice: 550,
      offer: "-25%",
    },
  ],
  thisMonth: [
    {
      id: 5,
      image: redJacketImg,
      productName: "The north coat",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 6,
      image: bagImg,
      productName: "Gucci duffle bag",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 7,
      image: cpucoolerImg,
      productName: "RGB liquid CPU Cooler",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 8,
      image: bookshell,
      productName: "Small BookShelf",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
  ],
  ourProducts: [
    {
      id: 9,
      image: chocolate,
      productName: "Breed Dry Dog Food",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 10,
      image: dslr,
      productName: "CANON EOS DSLR Camera",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 11,
      image: laptop,
      productName: "ASUS FHD Gaming Laptop",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 12,
      image: cream,
      productName: "Curology Product Set",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 13,
      image: babycar,
      productName: "Kids Electric Car",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 14,
      image: boot,
      productName: "Jr. Zoom Soccer Cleats",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 15,
      image: gamepad,
      productName: "GP11 Shooter USB Gamepad",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 16,
      image: jacketImg,
      productName: "Winter Jacket",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 17,
      image: gamepad,
      productName: "GP11 Shooter USB Gamepad",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
    {
      id: 18,
      image: jacketImg,
      productName: "Winter Jacket",
      rating: 4.9,
      starCount: 500,
      oldPrice: 650,
      newPrice: 550,
      offer: "-15%",
    },
  ]
};

export default products;
